server:
  port: 8085

spring:
  main:
    web-application-type: servlet
  application:
    name: media-service
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms
  cache:
    type: redis
    redis:
      time-to-live: 600000
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/oose_db?timezone=Asia/Ho_Chi_Minh
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: http://${GATEWAY_URL:localhost}:8222
    description: API Gateway (Development)

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Expose prometheus endpoint
  metrics:
    export:
      prometheus:
        enabled: true
