server:
  port: 8087
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never
    include-exception: false
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: servlet
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/oose_db?timezone=Asia/Ho_Chi_Minh
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost}:9092
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: com.example.commondto.dto.request,com.example.commondto.dto.response

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:eureka-server}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  server:
    url: http://${GATEWAY_URL:localhost}:8222
    description: API Gateway (Development)

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Expose prometheus endpoint
  metrics:
    export:
      prometheus:
        enabled: true
vnpay:
  tmn_code: 9G98XPFA
  secret_key: WCX7S6F8LPB0JKMZWNU8U2MTCI1J9DK7
  api_url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return_url: https://noncompliantly-pseudomodest-latonya.ngrok-free.dev/api/payments/vnpay-return
  version: 2.1.0
  curr_code: VND